call mvn install:install-file -Dfile=./csv.jar -DgroupId=com.csvreader -DartifactId=csv -Dversion=1.0 -Dpackaging=jar
call mvn install:install-file -Dfile=./gt-api-14.5.jar -DgroupId=org.geotools -DartifactId=gt-api -Dversion=14.5 -Dpackaging=jar
call mvn install:install-file -Dfile=./gt-arcgrid-14.5.jar -DgroupId=org.geotools -DartifactId=gt-arcgrid -Dversion=14.5 -Dpackaging=jar
call mvn install:install-file -Dfile=./gt-coverage-14.5.jar -DgroupId=org.geotools -DartifactId=gt-coverage -Dversion=14.5 -Dpackaging=jar
call mvn install:install-file -Dfile=./gt-data-14.5.jar -DgroupId=org.geotools -DartifactId=gt-data -Dversion=14.5 -Dpackaging=jar
call mvn install:install-file -Dfile=./gt-image-14.5.jar -DgroupId=org.geotools -DartifactId=gt-image -Dversion=14.5 -Dpackaging=jar
call mvn install:install-file -Dfile=./gt-main-14.5.jar -DgroupId=org.geotools -DartifactId=gt-main -Dversion=14.5 -Dpackaging=jar
call mvn install:install-file -Dfile=./gt-metadata-14.5.jar -DgroupId=org.geotools -DartifactId=gt-metadata -Dversion=14.5 -Dpackaging=jar
call mvn install:install-file -Dfile=./gt-opengis-14.5.jar -DgroupId=org.opengis -DartifactId=gt-opengis -Dversion=14.5 -Dpackaging=jar
call mvn install:install-file -Dfile=./gt-referencing-14.5.jar -DgroupId=org.geotools -DartifactId=gt-referencing -Dversion=14.5 -Dpackaging=jar
call mvn install:install-file -Dfile=./gt-render-14.5.jar -DgroupId=org.geotools -DartifactId=gt-render -Dversion=14.5 -Dpackaging=jar
call mvn install:install-file -Dfile=./gt-shapefile-14.5.jar -DgroupId=org.geotools -DartifactId=gt-shapefile -Dversion=14.5 -Dpackaging=jar
call mvn install:install-file -Dfile=./imageio-ext-geocore-1.1.13.jar -DgroupId=it.geosolutions -DartifactId=imageio-ext-geocore -Dversion=1.1.13 -Dpackaging=jar
call mvn install:install-file -Dfile=./imageio-ext-imagereadmt-1.1.13.jar -DgroupId=it.geosolutions -DartifactId=imageio-ext-imagereadmt -Dversion=1.1.13 -Dpackaging=jar
call mvn install:install-file -Dfile=./imageio-ext-imagereadmt-1.1M012010.jar -DgroupId=it.geosolutions -DartifactId=imageio-ext-imagereadmt -Dversion=1.1M012010 -Dpackaging=jar
call mvn install:install-file -Dfile=./imageio-ext-streams-1.1.13.jar -DgroupId=it.geosolutions -DartifactId=imageio-ext-streams -Dversion=1.1.13 -Dpackaging=jar
call mvn install:install-file -Dfile=./imageio-ext-tiff-1.1.13.jar -DgroupId=it.geosolutions -DartifactId=imageio-ext-tiff -Dversion=1.1.13 -Dpackaging=jar
call mvn install:install-file -Dfile=./imageio-ext-utilities-1.1.13.jar -DgroupId=it.geosolutions -DartifactId=imageio-ext-utilities -Dversion=1.1.13 -Dpackaging=jar
call mvn install:install-file -Dfile=./imageJ.jar -DgroupId=ij -DartifactId=imageJ -Dversion=1.0 -Dpackaging=jar
call mvn install:install-file -Dfile=./jai_codec-1.1.3.jar -DgroupId=com.sun.media.jai -DartifactId=jai_codec -Dversion=1.1.3 -Dpackaging=jar
call mvn install:install-file -Dfile=./jai_core-1.1.3.jar -DgroupId=com.sun.media.jai -DartifactId=jai_core -Dversion=1.1.3 -Dpackaging=jar
call mvn install:install-file -Dfile=./jai_imageio-1.1.jar -DgroupId=com.sun.media.jai -DartifactId=jai_imageio -Dversion=1.1 -Dpackaging=jar
call mvn install:install-file -Dfile=./miglayout-3.7-swing.jar -DgroupId=net.miginfocom -DartifactId=miglayout -Dversion=3.7 -Dpackaging=jar
call mvn install:install-file -Dfile=./antlr-4.4-complete.jar -DgroupId=org.antlr -DartifactId=antlr -Dversion=4.4 -Dpackaging=jar
call mvn install:install-file -Dfile=./choco-solver-3.3.3-with-dependencies.jar -DgroupId=org.chocosolver -DartifactId=choco -Dversion=3.3.3 -Dpackaging=jar
call mvn install:install-file -Dfile=./poi-3.15.jar -DgroupId=org.apache.poi -DartifactId=poi -Dversion=3.15 -Dpackaging=jar
call mvn install:install-file -Dfile=./poi-ooxml-3.15.jar -DgroupId=org.apache.poi -DartifactId=poi-ooxml -Dversion=3.15 -Dpackaging=jar
call mvn install:install-file -Dfile=./poi-ooxml-schemas-3.15.jar -DgroupId=org.apache.poi -DartifactId=poi-ooxml-schemas -Dversion=3.15 -Dpackaging=jar
call mvn install:install-file -Dfile=./xmlbeans-2.6.0.jar -DgroupId=org.apache.xmlbeans -DartifactId=xmlbeans -Dversion=2.6.0 -Dpackaging=jar
call mvn install:install-file -Dfile=./commons-collections4-4.1.jar -DgroupId=org.apache.commons -DartifactId=commons-collections4 -Dversion=4.1 -Dpackaging=jar
